#!/usr/bin/python

from bac import *

while True:
    try:
        cmd = input('> ').split()
        if len(cmd) == 0:
            continue
        elif cmd[0] == 'summary':
            if len(cmd) == 1:
                format_str = '{:<6} {:<6} {:<6} {:<6} {:<6} {:<6}'
                print(format_str.format('room', 'mode', 'setpt',
                                        'temp', 'fan', 'dir'))
                for room in sorted(rooms.keys()):
                    print(format_str.format(room,
                                            get_status(room),
                                            get_setpoint(room),
                                            get_temperature(room),
                                            get_fan_speed(room),
                                            get_air_direction(room)))
            else:
                print('Usage: summary')
        elif cmd[0] == 'get':
            if len(cmd) == 2:
                format_str = '{:<6} {:<6} {:<6} {:<6} {:<6}'
                print(format_str.format('mode', 'setpt',
                                        'temp', 'fan', 'dir'))
                print(format_str.format(get_status(cmd[1]),
                                        get_setpoint(cmd[1]),
                                        get_temperature(cmd[1]),
                                        get_fan_speed(cmd[1]),
                                        get_air_direction(cmd[1])))
            elif len(cmd) == 3:
                room, property = cmd[1], cmd[2]
                function = {'mode': get_status,
                            'setpt': get_setpoint,
                            'temp': get_temperature,
                            'fan': get_fan_speed,
                            'dir': get_air_direction}[cmd[2]]
                print(function(cmd[1]))
            else:
                print('Usage: get room [property]')
        elif cmd[0] == 'set':
            if len(cmd) == 4:
                function = {'mode': set_status,
                            'setpt': set_setpoint,
                            'fan': set_fan_speed,
                            'dir': set_air_direction}[cmd[2]]
                function(cmd[1], cmd[3])
            else:
                print('Usage: set room property value')
        elif cmd[0] == 'exit':
            exit()
        else:
            print('Commands: summary get set exit')
            print('Rooms: {}'.format(' '.join(sorted(rooms.keys()))))
            print('Properties: mode setpt temp fan dir')
            print('Values (mode): off {}'.format(' '.join(modes[1:])))
            print('Values (fan): {}'.format(' '.join(fan_speeds[1:])))
            print('Values (dir): {}'.format(' '.join(air_directions[1:])))
    except EOFError:
        exit()
    except KeyboardInterrupt:
        exit()
    except:
        print("Error.")
        continue
